from enum import Enum

class Attribute(Enum):
    FREE_CASH_FLOW_OFFSET = 14
    OPERATING_CASH_FLOW_OFFSET = 19
    CAPITAL_EXPENDITURE_OFFSET = 19
    REVENUE_OFFSET = 13
    TOTAL_DEBT_OFFSET = 10

